main = ".open-next/worker.js"
name = "personal-site"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.local]
# Local development environment
# Use this for local preview: wrangler dev --env local